// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: car.proto

package proto;

public interface CarOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Car)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string brand = 3;</code>
   */
  java.lang.String getBrand();
  /**
   * <code>string brand = 3;</code>
   */
  com.google.protobuf.ByteString
      getBrandBytes();

  /**
   * <code>string manufacturingYear = 4;</code>
   */
  java.lang.String getManufacturingYear();
  /**
   * <code>string manufacturingYear = 4;</code>
   */
  com.google.protobuf.ByteString
      getManufacturingYearBytes();

  /**
   * <code>string modelYear = 5;</code>
   */
  java.lang.String getModelYear();
  /**
   * <code>string modelYear = 5;</code>
   */
  com.google.protobuf.ByteString
      getModelYearBytes();

  /**
   * <code>double price = 6;</code>
   */
  double getPrice();
}
