// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: car.proto

package proto;

public final class CarOuterClass {
  private CarOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Car_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Car_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CreateCarRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CreateCarRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CreateCarResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CreateCarResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DeleteCarRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_DeleteCarRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DeleteCarResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_DeleteCarResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GetCarRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_GetCarRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GetCarResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_GetCarResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ListCarRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ListCarRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ListCarResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ListCarResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UpdateCarRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_UpdateCarRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UpdateCarResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_UpdateCarResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tcar.proto\022\005proto\"k\n\003Car\022\n\n\002id\030\001 \001(\005\022\014\n" +
      "\004name\030\002 \001(\t\022\r\n\005brand\030\003 \001(\t\022\031\n\021manufactur" +
      "ingYear\030\004 \001(\t\022\021\n\tmodelYear\030\005 \001(\t\022\r\n\005pric" +
      "e\030\006 \001(\001\"+\n\020CreateCarRequest\022\027\n\003car\030\001 \001(\013" +
      "2\n.proto.Car\",\n\021CreateCarResponse\022\027\n\003car" +
      "\030\001 \001(\0132\n.proto.Car\"!\n\020DeleteCarRequest\022\r" +
      "\n\005carId\030\001 \001(\005\"\"\n\021DeleteCarResponse\022\r\n\005ca" +
      "rId\030\001 \001(\005\"\036\n\rGetCarRequest\022\r\n\005carId\030\001 \001(" +
      "\005\")\n\016GetCarResponse\022\027\n\003car\030\001 \001(\0132\n.proto" +
      ".Car\"\020\n\016ListCarRequest\"*\n\017ListCarRespons" +
      "e\022\027\n\003car\030\001 \003(\0132\n.proto.Car\"+\n\020UpdateCarR" +
      "equest\022\027\n\003car\030\001 \001(\0132\n.proto.Car\",\n\021Updat" +
      "eCarResponse\022\027\n\003car\030\001 \001(\0132\n.proto.Car2\275\002" +
      "\n\nCarService\022>\n\tCreateCar\022\027.proto.Create" +
      "CarRequest\032\030.proto.CreateCarResponse\022>\n\t" +
      "DeleteCar\022\027.proto.DeleteCarRequest\032\030.pro" +
      "to.DeleteCarResponse\0225\n\006GetCar\022\024.proto.G" +
      "etCarRequest\032\025.proto.GetCarResponse\0228\n\007L" +
      "istCar\022\025.proto.ListCarRequest\032\026.proto.Li" +
      "stCarResponse\022>\n\tUpdateCar\022\027.proto.Updat" +
      "eCarRequest\032\030.proto.UpdateCarResponseB\002P" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_Car_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Car_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Car_descriptor,
        new java.lang.String[] { "Id", "Name", "Brand", "ManufacturingYear", "ModelYear", "Price", });
    internal_static_proto_CreateCarRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_CreateCarRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CreateCarRequest_descriptor,
        new java.lang.String[] { "Car", });
    internal_static_proto_CreateCarResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_CreateCarResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CreateCarResponse_descriptor,
        new java.lang.String[] { "Car", });
    internal_static_proto_DeleteCarRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_DeleteCarRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_DeleteCarRequest_descriptor,
        new java.lang.String[] { "CarId", });
    internal_static_proto_DeleteCarResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_DeleteCarResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_DeleteCarResponse_descriptor,
        new java.lang.String[] { "CarId", });
    internal_static_proto_GetCarRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_proto_GetCarRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_GetCarRequest_descriptor,
        new java.lang.String[] { "CarId", });
    internal_static_proto_GetCarResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_proto_GetCarResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_GetCarResponse_descriptor,
        new java.lang.String[] { "Car", });
    internal_static_proto_ListCarRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_proto_ListCarRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ListCarRequest_descriptor,
        new java.lang.String[] { });
    internal_static_proto_ListCarResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_proto_ListCarResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ListCarResponse_descriptor,
        new java.lang.String[] { "Car", });
    internal_static_proto_UpdateCarRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_proto_UpdateCarRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_UpdateCarRequest_descriptor,
        new java.lang.String[] { "Car", });
    internal_static_proto_UpdateCarResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_proto_UpdateCarResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_UpdateCarResponse_descriptor,
        new java.lang.String[] { "Car", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
